<?php

/**
 * @file
 * Adds accordion plugin to CKEditor.
 */

/**
 * Implements hook_ckeditor_plugins().
 *
 * Register the CKEditor plugin - it appears in the plugins list of content
 * format settings.
 */
function ckeditor_accordion_ckeditor_plugins() {
  $plugin_path = backdrop_get_path('module', 'ckeditor_accordion') . '/plugins/accordion/';
  return array(
    'accordion' => array(
      'path' => $plugin_path,
      'file' => 'plugin.js',
      'css' => array($plugin_path . '/accordion.css'),
      'buttons' => array(
        'Accordion' => array(
          'label' => t('Accordion'),
          'image' => $plugin_path . '/icons/accordion.png',
          'dependencies' => array('contextmenu'),
        ),
      ),
      'required_html' => array(
        array('dl', 'dd', 'dt'),
      ),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ckeditor_accordion_menu() {

  $items = array();

  $items['admin/config/content/ckeditor_accordion'] = array(
    'title' => 'Administer CKEditor Accordion',
    'description' => 'Adminster CKEditor Accordion configuration',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('ckeditor_accordion_admin'),
    'access arguments' => array('administer filters'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_config_info().
 */
function ckeditor_accordion_config_info() {
  $prefixes['ckeditor_accordion.settings'] = array(
    'label' => t('CKEditor Accordion settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Create settings page for the module.
 */
function ckeditor_accordion_admin() {
  $form = array();
  $form['#config'] = 'ckeditor_accordion.settings';

  $form['ckeditor_accordion_collapsed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Collapse all tabs by default'),
    '#default_value' => config_get('ckeditor_accordion.settings', 'ckeditor_accordion_collapsed'),
    '#description' => t("The maximum number of links to display in the block."),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ckeditor_accordion_preprocess_page(&$variables) {
  $config = config_get('ckeditor_accordion.settings', 'ckeditor_accordion_collapsed');
  if ($config) {
    backdrop_add_js(array('ckeditor_accordion' => array('collapseAll' => 1)), array('type' => 'setting'));
  }
}
